export { mapRailSegment, mapRailSegments } from "./railsMapper.js";
export type { MappedRailSegments } from "./railsMapper.js";
export { mapResourceNode, mapResourceNodes } from "./resourceNodesMapper.js";
export type { MappedResourceNodes } from "./resourceNodesMapper.js";
export { mapTrain, mapTrains } from "./trainsMapper.js";
export type { MappedTrains } from "./trainsMapper.js";
export { mapTrainStation, mapTrainStations } from "./stationsMapper.js";
export type { MappedTrainStations } from "./stationsMapper.js";
export { toWholeMetres, inWholeMetreBounds, MAX_WHOLE_METRES } from "./coordinates.js";
export { mapNodeType } from "./nodeType.js";
